### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by OHeroJ** [vapor-community/VaporMonitoring#4]
ubantu 16.04 :  error while loading shared libraries: libmemplugin.so: cannot open shared object file: No such file or directory

**Comment by MrLotU** [comment]
Hi @OHeroJ thanks for raising the issue. How exactly are you running your app?

**Comment by snakecharmer** [comment]
I have the same problem. it happens using the docker file provided by Vapor

**Comment by ascuderibjss** [comment]
Hi,
I've solved the issue by adding a COPY line for the *.so in the Vapor Docker file
and by adding the swiftmetrics.properties configuration.
You need to download it from https://github.com/RuntimeTools/SwiftMetrics/blob/master/swiftmetrics.properties and copy it in the same directory of the Docker file.
...
FROM ubuntu:16.04
ARG env
RUN apt-get -qq update && apt-get install -y \
  libicu55 libxml2 libbsd0 libcurl3 libatomic1 \
  tzdata \
  && rm -r /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /build/bin/Run .
**COPY --from=builder /build/bin/*.so /app/
COPY swiftmetrics.properties .**
...
